---
- hosts: localhost
  become: yes
  tasks:
     name:  create ansible nodes
     ec2: 
     key_name: redhatoregon 
     instance_type: t2.micro
     image: ami-05cbe9c559ef7b896
     group: mySG23NewDec
     count: 2
     region: "us-west-2"
     vpc_subnet_id: subnet-01d83f50aab8ce3a1
     assign_public_ip: yes
     instance_tags:
       name: ansiblenode