---
- name: update
  apt:
  update_cache: yes
- name: install java
  apt:
  name: default_jdk
  stste: present










---
- name: update
  apt:
  update_cache: yes
- name: install java 
  apt: 
    name: default-jdk
    state: present